version: "2"
services:
  ldap:
    image: welharrak/ldapserver19:latest
    container_name: ldapserver
    hostname: ldapserver
    ports: 
      - "389:389"
    networks:
     - ldapnet
  samba:
    image: welharrak/samba19:pam
    container_name: samba
    hostname: samba
    volumes:
      - "homes:/tmp/home"
    ports:
      - "139:139"
      - "445:445"
    networks:
     - ldapnet
  pam:
    image: welharrak/pam19:samba
    container_name: pam
    hostname: pam
    networks:
     - ldapnet
    privileged: true
networks:
    ldapnet:
volumes:
    homes:
